-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 021: Quiz visibility fix — application-layer only, no data change
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Problem:
--   The learner quiz page queried ONLY WHERE module_id = <current-module>.
--   Quizzes attached to a lesson (lesson_id set, module_id NULL) were
--   invisible to learners even though data was correct and RLS allowed access.
--
-- Why no SQL backfill:
--   The quizzes_single_parent CHECK constraint (migration 004) enforces that
--   exactly one of (module_id, lesson_id) is non-null.  Any attempt to set
--   both on an existing row would violate the constraint.  The existing data
--   is already correct — no rows need to change.
--
-- Fix applied in application code (same commit):
--   1. learner quiz page — added a two-step lookup:
--        (a) SELECT ... WHERE module_id = resolvedId   (module-level quiz)
--        (b) If nothing found, SELECT ... WHERE lesson_id IN (<module lessons>)
--      This covers both attachment styles transparently.
--
--   2. updateQuiz server action — removed the resolver block that was trying
--      to set both module_id AND lesson_id on update, which would have
--      violated quizzes_single_parent on save.  Now mirrors createQuiz:
--        module_id: lessonId ? null : moduleId
--        lesson_id: lessonId ?? null
--
-- This migration is intentionally a no-op.  It is kept so the migration
-- sequence number is reserved and deployment scripts do not skip it.
-- ═══════════════════════════════════════════════════════════════════════════

SELECT 1; -- no-op
